apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "r-studio.fullname" . }}
  labels:
    app: {{ template "r-studio.name" . }}
    chart: {{ template "r-studio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "r-studio.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "r-studio.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: {{ template "r-studio.fullname" . }}-storage
              mountPath: /home
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: {{ template "r-studio.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ template "r-studio.fullname" . }}
