apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "jupyter-python-nbk.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "jupyter-python-nbk.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "jupyter-python-nbk.fullname" . }}
{{- with .Values.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1000:100 /mnt/data"]
          volumeMounts:
            - name: task-pv-storage
              mountPath: /mnt/data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: task-pv-storage
              mountPath: /notebooks-dir
          #livenessProbe:
           # httpGet:
            #  path: /
             # port: http
          #readinessProbe:
           # httpGet:
            #  path: /
             # port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: {{ template "jupyter-python-nbk.fullname" . }}
#    {{- with .Values.nodeSelector }}
#      nodeSelector:
#{{ toYaml . | indent 8 }}
#    {{- end }}
#    {{- with .Values.affinity }}
#      affinity:
#{{ toYaml . | indent 8 }}
#    {{- end }}
#    {{- with .Values.tolerations }}
#      tolerations:
#{{ toYaml . | indent 8 }}
#    {{- end }}


