# Default values for r-studio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: saagie/rstudio
  tag: sp1.15.0-mesos1.3.1-spark2.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8787

ingress:
  enabled: false

## Persist data to a persistent volume
persistence:
  accessMode: ReadWriteOnce
  size: 2Gi

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2.0
    memory: 6Gi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
